### ISSUE TITLE
`option+s` does not work in OSX 10.11.6

### ISSUE THREAD

**Issue by Edenharder** [patrick-zippenfenig/us-with-german-umlauts#2]
As I test, only `option+s` does not work in OSX 10.11.6, is there any way to fix this?

[A long key-press to bring up alternates to a letter](https://www.quora.com/How-do-I-make-symbols-on-a-Mac), I'm using this method currently.

**Comment by patrick-zippenfenig** [comment]
10.11.6 is quite old. You could try to use Ukelele to generate a new layout and test if ``ß`` can be used.
