### ISSUE TITLE
Missing "long-press" menu for further accents

### ISSUE THREAD

**Issue by ranuss** [patrick-zippenfenig/us-with-german-umlauts#3]
I am missing the menu for further accents (example: õ, ø, œ usw.) when i do a long press on a key. Is there a chance to get this back?

**Comment by patrick-zippenfenig** [comment]
I am not sure. Maybe the layout needs to regenerated to include these features. Maybe in the next days I will have a look into it.

**Comment by ranuss** [comment]
Is there any update on this?

**Comment by patrick-zippenfenig** [comment]
Hi, sorry for not getting back earlier. The keyboard layout bundle is not controlling the long press context menu.

You can enable it with ``defaults write -g ApplePressAndHoldEnabled -bool true`` 

More information here: https://fvdm.com/code/fix-for-not-working-accent-menu-macos

Long press menu is working fine on my mac using this custom US German keyboard layout

Best, Patrick
