### ISSUE TITLE
opt + a führt zu å anstatt zu ä

### ISSUE THREAD

**Issue by JoshuaSchumacherGER** [patrick-zippenfenig/us-with-german-umlauts#5]
Siehe Titel.

**Comment by JoshuaSchumacherGER** [comment]
Neustart behob den Fehler :)

**Comment by 12finger** [comment]
passiert wieder in 15.2  Sequoia 
  any ideas jemand?
benutzt noch jemand dieses .keylaout? und kann helfen?

**Comment by patrick-zippenfenig** [comment]
Funktioniert problemlos bei mir mit 15.2
