### ISSUE TITLE
No time for typing in the password 

### ISSUE THREAD

**Issue by walefisch** [patrick-zippenfenig/us-with-german-umlauts#7]
On macos ventura (13.0.1) there is not enough time for typing in the password. This leads to the keyboard layout notbinstalling at all.

in the terminal it says: zsh: done                   curl -sL  | 
zsh: suspended (tty input)  sudo tar xz --exclude=README.md --strip=1 -C /Library/Keyboard\ Layouts/

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I can confirm it also happens on my Mac with macOS Ventura. I am not sure why the behaviour is now different. Small workaround:

```bash
sudo su
# Enter password to switch to root
curl -sL https://api.github.com/repos/patrick-zippenfenig/us-with-german-umlauts/tarball/master | sudo tar xz --exclude=README.md --strip=1 -C /Library/Keyboard\ Layouts/
exit
```

**Comment by walefisch** [comment]
thank you!
